name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rameshkumar456/frontend:latest 
      - name: executing remote ssh commands using password
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f $(docker ps -aq -f name=frontend)
            docker rmi $(docker images | grep 'rameshkumar456/frontend:latest' | awk '{print $3}')
            docker pull rameshkumar456/frontend:latest
            docker run --name frontend -p 8080:3000 --restart=always -d rameshkumar456/frontend:latest
