name: Docker

 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 

jobs:

 

  build:

 

    runs-on: ubuntu-latest

 

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/image
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/image
    - name: Run the container
      run: |
        docker run \
           -e MY_VAR=myvalue \
           -p 8080:3000 \
           ${{ secrets.DOCKER_USERNAME }}/image

 

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
