name: ci

on:
  push:
    branches:
      - "main"

needs: publish_to_docker
  runs-on: ubuntu-latest
   steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rm -f $(docker ps -aq -f name=frontend)
            docker rmi $(docker images | grep 'rameshkumar456/frontend' | awk '{print $3}')
            docker pull rameshkumar456/frontend
            docker run --name frontend -p 8080:3000 --restart=always -d rameshkumar456/frontend
